# @package _global_

defaults:
  - _self_
  - data: mnist.yaml
  - model: mnist.yaml
  # experiment configs allow for version control of specific hyperparameters
  # e.g. best hyperparameters for given model and datamodule
  - experiment: null

seed: 42

root_dir: . # path to data directory
output_dir: ${hydra:runtime.output_dir} # task name, determines output directory path
task_name: "train"

train: True
test: True
ckpt_path: null

trainer:
  _target_: lightning.pytorch.trainer.Trainer
  default_root_dir: ${output_dir}
  min_epochs: 1
  max_epochs: 10
  accelerator: cpu
  devices: 1
  check_val_every_n_epoch: 1

# hydra
hydra:
  # enable color logging
  defaults:
    - override hydra_logging: colorlog
    - override job_logging: colorlog

  run:
    dir: ${root_dir}/logs/${task_name}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}
  sweep:
    dir: ${root_dir}/logs/${task_name}/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ${hydra.job.num}
