# @package _global_

defaults:
  - _self_
  - data: mnist.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: mnist.yaml
  - logger: null
  - trainer: default.yaml
  - hydra: default.yaml

root_dir: .

# path to data directory
data_dir: ${root_dir}/data/

# path to logging directory
log_dir: ${root_dir}/logs/

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${hydra:runtime.output_dir}

# path to working directory
work_dir: ${hydra:runtime.cwd}

# ask user for tags if none are provided in the config
enforce_tags: True

# pretty print config tree at the start of the run using Rich library
print_config: True

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
